application:
  name: attendance-tracker
  project: Attendance Site
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: attendance
routers:
  - name: main
    routes:
      - application_name: attendance-tracker
        paths:
          - /
