---
application:
  name: "attendance-tracker"
  project: "Attendance Site"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "attendance"
  version: "11"
routers:
- name: "main-attendance-tracker"
  routes:
  - application_name: "attendance-tracker"
    paths:
    - "/*"
