---
application:
  name: "djpg"
  project: "raeson"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "djpg"
  version: "11"
routers:
- name: "main-djpg"
  routes:
  - application_name: "djpg"
    paths:
    - "/*"
